import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#e1fcfcff",
    paddingHorizontal: 24,
  },
  langSwitcher: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    padding: 4,
    paddingHorizontal: 8,
    borderRadius: 8,
    backgroundColor: "#f2f2f2",
  },
  langText: {
    fontSize: 14,
    fontWeight: "bold",
    color: "#333",
  },
  logoContainer: {
    alignItems: "center",
    marginTop: 60,
    marginBottom: 40,
  },
  logoPlaceholder: {
    width: 120,
    height: 120,
    backgroundColor: "#f0f0f0",
    borderRadius: 60,
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 2,
    borderColor: "#e0e0e0",
  },
  logoText: {
    fontSize: 18,
    fontWeight: "bold",
    color: "#666",
  },
  descriptionContainer: {
    alignItems: "center",
    marginBottom: 20,
    paddingHorizontal: 20,
  },
  descriptionText: {
    fontSize: 24,
    color: "#2c3e50",
    textAlign: "center",
    lineHeight: 36,
    marginBottom: 12,
  },
  subDescriptionText: {
    fontSize: 16,
    color: "#7f8c8d",
    textAlign: "center",
    lineHeight: 24,
  },
  buttonsContainer: {
    marginBottom: 10,
  },
  primaryButton: {
    // backgroundColor: "linear-gradient(90deg, #4f8cff 0%, #1cb5e0 100%)",
    paddingVertical: 16,
    paddingHorizontal: 32,
    borderRadius: 16,
    alignItems: "center",
    marginBottom: 20,
    borderWidth: 1,
    borderColor: "#1cb5e0",
    shadowColor: "#1cb5e0",
    shadowOffset: {
      width: 0,
      height: 6,
    },
    shadowOpacity: 0.25,
    shadowRadius: 12,
    elevation: 6,
  },
  primaryButtonText: {
    color: "#1cb5e0",
    fontSize: 20,
    fontWeight: "bold",
    letterSpacing: 1,
  },
  secondaryButton: {
    backgroundColor: "transparent",
    paddingVertical: 16,
    paddingHorizontal: 24,
    borderRadius: 12,
    alignItems: "center",
    borderWidth: 0,
    borderColor: "#bdc3c7",
  },
  secondaryButtonText: {
    color: "#2c3e50",
    fontSize: 18,
    fontWeight: "500",
  },
  footerContainer: {
    flex: 1,
    justifyContent: "flex-end",
    alignItems: "center",
    paddingBottom: 40,
  },
  teacherSignupContainer: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 20,
  },
  teacherText: {
    fontSize: 16,
    color: "#7f8c8d",
  },
  teacherLink: {
    fontSize: 16,
    color: "#3498db",
    textDecorationLine: "underline",
  },
  contactContainer: {
    paddingVertical: 8,
  },
  contactText: {
    fontSize: 16,
    color: "#e74c3c",
    fontWeight: "500",
  },
});
