import { useTranslationContext } from "@/context/TranslationContext";
import { getFontWeight } from "@/theme";
import { AppStyles, Theme, TypedStyleSheet } from "@/types/style";
import { I18nManager, Platform, StyleSheet } from "react-native";

export const createStyles = (theme: Theme): TypedStyleSheet<AppStyles> => {
  const { language } = useTranslationContext();
  const isRTL = language === "ar";

  return StyleSheet.create<AppStyles>({
    container: {
      flex: 1,
      backgroundColor: theme.background.primary,
      paddingHorizontal: 20,
    },
    scrollView: {
      flex: 1,
    },
    scrollContent: {
      flexDirection: "column",
      alignItems: isRTL ? "flex-end" : "flex-start",
    },
    header: {
      flexDirection: isRTL ? "row-reverse" : "row",
      justifyContent: "space-between",
      alignItems: "center",
      padding: theme.spacing.base,
    },
    headerTitle: {
      fontSize: theme.fontSize["lg"],
      fontWeight: getFontWeight(theme.fontWeight.bold),
      color: theme.text.link,
      textAlign: isRTL ? "right" : "left",
      includeFontPadding: false,
      textAlignVertical: "center",
    },
    headerSubtitle: {
      fontSize: theme.fontSize["md"],
      fontWeight: getFontWeight(theme.fontWeight.medium),
      color: theme.text.secondary,
      textAlign: "center",
      includeFontPadding: false,
      textAlignVertical: "center",
    },
    headerContainer: {
      flexDirection: "column",
      alignItems: isRTL ? "flex-start" : "flex-end",
      margin: theme.spacing.base,
    },
    card: {
      backgroundColor: theme.background.card,
      margin: theme.spacing.base,
      padding: theme.spacing.base,
      borderRadius: theme.borderRadius.lg,
      ...Platform.select({
        ios: {
          shadowColor: "#000",
          shadowOffset: { width: 0, height: 2 },
          shadowOpacity: 0.25,
          shadowRadius: 3.84,
        },
        android: {
          elevation: 5,
        },
      }),
    },
    cardTitle: {
      fontSize: theme.fontSize.lg,
      fontWeight: getFontWeight(theme.fontWeight.semibold),
      color: theme.text.primary,
      marginBottom: theme.spacing.sm,
      textAlign: isRTL ? "right" : "left",
      includeFontPadding: false,
      textAlignVertical: "center",
    },
    cardDescription: {
      fontSize: theme.fontSize.base,
      color: theme.text.secondary,
      marginBottom: theme.spacing.base,
      lineHeight: 22,
      textAlign: isRTL ? "right" : "left",
      includeFontPadding: false,
    },
    difficultyBadge: {
      backgroundColor: theme.learning.difficulty.easy,
      alignSelf: isRTL ? "flex-end" : "flex-start",
      paddingHorizontal: theme.spacing.sm,
      paddingVertical: theme.spacing.xs,
      borderRadius: theme.borderRadius.base,
      marginBottom: theme.spacing.base,
    },
    mediumDifficulty: {
      backgroundColor: theme.learning.difficulty.medium,
    },
    badgeText: {
      fontSize: theme.fontSize.sm,
      fontWeight: getFontWeight(theme.fontWeight.medium),
      color: theme.text.inverse,
      textAlign: isRTL ? "right" : "left",
      includeFontPadding: false,
      textAlignVertical: "center",
    },
    gradient: {
      borderRadius: 16,
      marginBottom: 10,
      ...Platform.select({
        ios: {
          shadowColor: "#1cb5e0",
          shadowOffset: { width: 0, height: 6 },
          shadowOpacity: 0.25,
          shadowRadius: 12,
        },
        android: {
          elevation: 6,
        },
      }),
    },
    primaryButton: {
      paddingVertical: 16,
      paddingHorizontal: 24,
      borderRadius: 16,
      alignItems: "center",
      justifyContent: "center",
    },
    primaryText: {
      color: "#fff",
      fontSize: 18,
      letterSpacing: 1,
      textAlign: "center",
      includeFontPadding: false,
      textAlignVertical: "center",
    },
    secondaryButton: {
      backgroundColor: "transparent",
      alignItems: "center",
      justifyContent: "center",
      paddingVertical: 16,
      paddingHorizontal: 24,
    },
    secondaryText: {
      color: "#2c3e50",
      fontSize: 18,
      textDecorationLine: "underline",
      textAlign: "center",
      includeFontPadding: false,
      textAlignVertical: "center",
    },
    quizButton: {
      backgroundColor: theme.learning.quiz,
      paddingVertical: theme.spacing.sm,
      paddingHorizontal: theme.spacing.base,
      borderRadius: theme.borderRadius.base,
      alignItems: "center",
      justifyContent: "center",
    },
    buttonText: {
      color: theme.text.inverse,
      fontSize: theme.fontSize.base,
      fontWeight: getFontWeight(theme.fontWeight.medium),
      textAlign: "center",
      includeFontPadding: false,
      textAlignVertical: "center",
    },
    secondaryButtonText: {
      color: theme.brand.primary,
      fontSize: theme.fontSize.base,
      fontWeight: getFontWeight(theme.fontWeight.medium),
      textAlign: "center",
      includeFontPadding: false,
      textAlignVertical: "center",
    },
    progressContainer: {
      marginBottom: theme.spacing.base,
    },
    progressBar: {
      height: 8,
      backgroundColor: theme.ui.divider,
      borderRadius: theme.borderRadius.base,
      overflow: "hidden",
      marginBottom: theme.spacing.xs,
    },
    progressFill: {
      height: "100%",
      backgroundColor: theme.learning.progress,
    },
    progressText: {
      fontSize: theme.fontSize.sm,
      color: theme.text.secondary,
      textAlign: isRTL ? "left" : "right",
      includeFontPadding: false,
      textAlignVertical: "center",
    },
    statsContainer: {
      flexDirection: isRTL ? "row-reverse" : "row",
      justifyContent: "space-around",
      backgroundColor: theme.background.card,
      margin: theme.spacing.base,
      padding: theme.spacing.base,
      borderRadius: theme.borderRadius.lg,

      ...Platform.select({
        ios: {
          shadowColor: "#000",
          shadowOffset: { width: 0, height: 2 },
          shadowOpacity: 0.1,
          shadowRadius: 3.84,
        },
        android: {
          elevation: 2,
        },
      }),
    },
    statItem: {
      alignItems: "center",
      justifyContent: "center",
    },
    statNumber: {
      fontSize: theme.fontSize["3xl"],
      fontWeight: getFontWeight(theme.fontWeight.bold),
      color: theme.brand.primary,
      textAlign: "center",
      includeFontPadding: false,
      textAlignVertical: "center",
    },
    statLabel: {
      fontSize: theme.fontSize.sm,
      color: theme.text.secondary,
      marginTop: theme.spacing.xs,
      textAlign: "center",
      includeFontPadding: false,
      textAlignVertical: "center",
    },
    whiteText: {
      color: "white",
      textAlign: isRTL ? "right" : "left",
      includeFontPadding: false,
      textAlignVertical: "center",
    },
    blackText: {
      color: "black",
      textAlign: isRTL ? "right" : "left",
      includeFontPadding: false,
      textAlignVertical: "center",
    },
    langText: {
      fontSize: 14,
      color: "#333",
      textAlign: isRTL ? "right" : "left",
      includeFontPadding: false,
      textAlignVertical: "center",
    },
    logoContainer: {
      alignItems: "center",
      justifyContent: "center",
      marginTop: 60,
      marginBottom: 40,
    },
    logoPlaceholder: {
      width: 120,
      height: 120,
      backgroundColor: "#f0f0f0",
      borderRadius: 60,
      justifyContent: "center",
      alignItems: "center",
      borderWidth: 2,
      borderColor: "#e0e0e0",
    },
    logoText: {
      fontSize: 18,
      color: "#666",
      textAlign: "center",
      includeFontPadding: false,
      textAlignVertical: "center",
    },
    descriptionContainer: {
      alignItems: "center",
      justifyContent: "center",
      marginBottom: 20,
      paddingHorizontal: 20,
    },
    descriptionText: {
      fontSize: 24,
      color: "#2c3e50",
      textAlign: "center",
      lineHeight: 36,
      marginBottom: 12,
      includeFontPadding: false,
    },
    subDescriptionText: {
      fontSize: 16,
      color: "#7f8c8d",
      textAlign: "center",
      lineHeight: 24,
      includeFontPadding: false,
    },
    buttonsContainer: {
      marginBottom: 10,
      flex: 1,
    },
    footerContainer: {
      flex: 1,
      justifyContent: "flex-end",
      alignItems: "center",
      paddingBottom: 40,
    },
    teacherSignupContainer: {
      flexDirection: isRTL ? "row-reverse" : "row",
      alignItems: "center",
      justifyContent: "center",
      marginBottom: 20,
    },
    teacherText: {
      fontSize: 16,
      color: "#7f8c8d",
      textAlign: isRTL ? "right" : "left",
      includeFontPadding: false,
      textAlignVertical: "center",
    },
    teacherLink: {
      fontSize: 16,
      color: "#3498db",
      textDecorationLine: "underline",
      textAlign: isRTL ? "right" : "left",
      includeFontPadding: false,
      textAlignVertical: "center",
    },
    contactContainer: {
      paddingVertical: 8,
      alignItems: "center",
      justifyContent: "center",
    },
    contactText: {
      fontSize: 16,
      color: "#e74c3c",
      fontWeight: "500",
      textAlign: isRTL ? "right" : "left",
      includeFontPadding: false,
      textAlignVertical: "center",
    },
    switcher: {
      flexDirection: isRTL ? "row-reverse" : "row",
      alignItems: "center",
      justifyContent: "center",
      gap: 4,
      paddingVertical: 6,
      paddingHorizontal: 10,
      borderRadius: 8,
      backgroundColor: theme.background.secondary,
      borderWidth: 1,
      borderColor: "#cbd5e1",
      minWidth: 55,
      marginRight: 0,
      marginLeft: 0,
    },
    preferencesContainer: {
      position: "absolute",
      top: Platform.OS === "ios" ? 50 : 40,
      [isRTL ? "right" : "left"]: 20,
      zIndex: 9999,
      flexDirection: isRTL ? "row-reverse" : "row",
      alignItems: "center",
      justifyContent: "center",
      gap: 8,
      backgroundColor: "transparent",
    },
    scrollContainer: {
      flex: 1,
    },
    formContainer: {
      padding: 10,
    },
    title: {
      fontSize: 24,
      textAlign: "center",
      marginBottom: 30,
      color: "#333",
      includeFontPadding: false,
      textAlignVertical: "center",
    },
    inputContainer: {
      marginBottom: 20,
    },
    label: {
      fontSize: 16,
      fontWeight: "600",
      marginBottom: 8,
      color: "#333",
      textAlign: isRTL ? "right" : "left",
      includeFontPadding: false,
      textAlignVertical: "center",
    },
    input: {
      borderWidth: 1,
      borderColor: "#ddd",
      borderRadius: 8,
      padding: 12,
      fontSize: 16,
      backgroundColor: "#fff",
      minHeight: 48,
      textAlign: isRTL ? "right" : "left",
      writingDirection: isRTL ? "rtl" : "ltr",
      includeFontPadding: false,
      textAlignVertical: "center",
      ...Platform.select({
        android: {
          paddingTop: 12,
          paddingBottom: 12,
        },
      }),
    },
    inputError: {
      borderColor: "#ff4444",
    },
    errorText: {
      color: "#ff4444",
      fontSize: 12,
      marginTop: 4,
      textAlign: isRTL ? "right" : "left",
      includeFontPadding: false,
      textAlignVertical: "center",
    },
    pickerContainer: {
      borderWidth: 1,
      borderColor: "#ddd",
      borderRadius: 8,
      backgroundColor: "#fff",
      overflow: "hidden",
    },
    pickerOption: {
      padding: 12,
      borderBottomWidth: 1,
      borderBottomColor: "#eee",
      justifyContent: "center",
      alignItems: isRTL ? "flex-end" : "flex-start",
    },
    pickerOptionSelected: {
      backgroundColor: "#007AFF",
    },
    pickerOptionText: {
      fontSize: 16,
      textAlign: isRTL ? "right" : "left",
      color: "#333",
      includeFontPadding: false,
      textAlignVertical: "center",
    },
    pickerOptionTextSelected: {
      color: "#fff",
      fontWeight: "600",
      textAlign: isRTL ? "right" : "left",
      includeFontPadding: false,
      textAlignVertical: "center",
    },
    teacherCard: {
      backgroundColor: theme.background.secondary,
      borderRadius: 12,
      padding: 16,
      marginBottom: 16,
      borderWidth: 1,
      borderColor: "#e5e7eb",
      ...Platform.select({
        ios: {
          shadowColor: "#000",
          shadowOffset: { width: 0, height: 2 },
          shadowOpacity: 0.1,
          shadowRadius: 3.84,
        },
        android: {
          elevation: 2,
        },
      }),
    },
    teacherHeader: {
      flexDirection: isRTL ? "row-reverse" : "row",
      marginBottom: 12,
      alignItems: "center",
    },
    teacherImage: {
      width: 60,
      height: 60,
      borderRadius: 30,
      [isRTL ? "marginLeft" : "marginRight"]: 12,
    },
    teacherInfo: {
      flex: 1,
      justifyContent: "center",
    },
    nameRatingRow: {
      flexDirection: isRTL ? "row-reverse" : "row",
      justifyContent: "space-between",
      alignItems: "center",
      marginBottom: 8,
    },
    teacherName: {
      fontSize: 18,
      color: "#1f2937",
      flex: 1,
      textAlign: isRTL ? "right" : "left",
      includeFontPadding: false,
      textAlignVertical: "center",
    },
    ratingContainer: {
      flexDirection: isRTL ? "row-reverse" : "row",
      alignItems: "center",
      justifyContent: "center",
    },
    starIcon: {
      fontSize: 14,
      [isRTL ? "marginLeft" : "marginRight"]: 4,
    },
    rating: {
      fontSize: 14,
      fontWeight: "600",
      color: "#6b7280",
      textAlign: isRTL ? "right" : "left",
      includeFontPadding: false,
      textAlignVertical: "center",
    },
    metaRow: {
      flexDirection: isRTL ? "row-reverse" : "row",
      justifyContent: "space-between",
      alignItems: "center",
    },
    specializationContainer: {
      flexDirection: isRTL ? "row-reverse" : "row",
      alignItems: "center",
      flex: 1,
    },
    graduationIcon: {
      fontSize: 14,
      [isRTL ? "marginLeft" : "marginRight"]: 4,
    },
    specialization: {
      fontSize: 14,
      color: "#2563eb",
      fontWeight: "500",
      textAlign: isRTL ? "right" : "left",
      includeFontPadding: false,
      textAlignVertical: "center",
    },
    studentsContainer: {
      flexDirection: isRTL ? "row-reverse" : "row",
      alignItems: "center",
      justifyContent: "center",
    },
    usersIcon: {
      fontSize: 14,
      [isRTL ? "marginLeft" : "marginRight"]: 4,
    },
    studentsText: {
      fontSize: 12,
      color: "#6b7280",
      textAlign: isRTL ? "right" : "left",
      includeFontPadding: false,
      textAlignVertical: "center",
    },
    bio: {
      fontSize: 14,
      color: "#4b5563",
      lineHeight: 20,
      marginBottom: 16,
      textAlign: isRTL ? "right" : "left",
      includeFontPadding: false,
    },
    materialsSection: {
      marginBottom: 16,
    },
    materialsTitle: {
      fontSize: 14,
      fontWeight: "600",
      color: "#374151",
      marginBottom: 8,
      textAlign: isRTL ? "right" : "left",
      includeFontPadding: false,
      textAlignVertical: "center",
    },
    materialsContainer: {
      flexDirection: isRTL ? "row-reverse" : "row",
      flexWrap: "wrap",
      gap: 8,
    },
    materialTag: {
      backgroundColor: "#dbeafe",
      paddingHorizontal: 12,
      paddingVertical: 6,
      borderRadius: 16,
      borderWidth: 1,
      borderColor: "#bfdbfe",
      alignItems: "center",
      justifyContent: "center",
    },
    materialText: {
      fontSize: 12,
      color: "#1d4ed8",
      fontWeight: "500",
      textAlign: "center",
      includeFontPadding: false,
      textAlignVertical: "center",
    },
    viewProfileButton: {
      backgroundColor: "#2563eb",
      paddingVertical: 12,
      borderRadius: 8,
      alignItems: "center",
      justifyContent: "center",
    },
    viewProfileText: {
      color: "#fff",
      fontSize: 16,
      fontWeight: "600",
      textAlign: "center",
      includeFontPadding: false,
      textAlignVertical: "center",
    },
    cardContainer: {
      width: "30%",
      alignItems: "center",
      justifyContent: "center",
      marginVertical: 10,
    },
    MaterialCard: {
      width: 50,
      height: 50,
      backgroundColor: theme.background.secondary,
      borderRadius: 12,
      marginBottom: 16,
      margin: 5,
      borderWidth: 1,
      borderColor: "#e5e7eb",

      ...Platform.select({
        ios: {
          shadowColor: "#000",
          shadowOffset: { width: 0, height: 2 },
          shadowOpacity: 0.1,
          shadowRadius: 3.84,
        },
        android: {
          elevation: 2,
        },
      }),
    },
    iconContainer: {
      alignItems: "center",
      justifyContent: "center",
      flex: 1,
      marginBottom: 0,
    },
    MaterialIcon: {
      fontSize: 25,
      marginBottom: 0,
    },
    MaterialTitle: {
      fontSize: 12,
      color: "#1f2937",
      textAlign: "center",
      includeFontPadding: false,
      textAlignVertical: "center",
    },
    MaterialDescription: {
      fontSize: 14,
      color: "#4b5563",
      textAlign: "center",
      lineHeight: 20,
      marginBottom: 20,
      includeFontPadding: false,
    },
    detailsContainer: {
      marginBottom: 20,
    },
    detailRow: {
      flexDirection: isRTL ? "row-reverse" : "row",
      justifyContent: "space-between",
      alignItems: "center",
      marginBottom: 12,
    },
    detailItem: {
      flexDirection: isRTL ? "row-reverse" : "row",
      alignItems: "center",
      justifyContent: "center",
    },
    detailIcon: {
      fontSize: 16,
      [isRTL ? "marginLeft" : "marginRight"]: 8,
    },
    detailLabel: {
      fontSize: 14,
      color: "#6b7280",
      textAlign: isRTL ? "right" : "left",
      includeFontPadding: false,
      textAlignVertical: "center",
    },
    detailValue: {
      fontSize: 14,
      fontWeight: "600",
      color: "#1f2937",
      textAlign: isRTL ? "right" : "left",
      includeFontPadding: false,
      textAlignVertical: "center",
    },
    exploreButton: {
      backgroundColor: "#7c3aed",
      paddingVertical: 14,
      borderRadius: 8,
      alignItems: "center",
      justifyContent: "center",
    },
    exploreButtonText: {
      color: "#fff",
      fontSize: 16,
      fontWeight: "600",
      textAlign: "center",
      includeFontPadding: false,
      textAlignVertical: "center",
    },
    modalOverlay: {
      flex: 1,
      backgroundColor: "rgba(0, 0, 0, 0.5)",
      justifyContent: "center",
      alignItems: "center",
      padding: 16,
    },
    modalContainer: {
      backgroundColor: "white",
      borderRadius: 32,
      width: "100%",
      maxWidth: 400,
      maxHeight: "80%",
      padding: 8,
      borderWidth: 1,
      borderColor: "#e0e7ef",

      ...Platform.select({
        ios: {
          shadowColor: "#000",
          shadowOffset: { width: 0, height: 8 },
          shadowOpacity: 0.18,
          shadowRadius: 16,
        },
        android: {
          elevation: 12,
        },
      }),
    },
    modalHeader: {
      flexDirection: isRTL ? "row-reverse" : "row",
      justifyContent: "space-between",
      alignItems: "center",
      padding: 20,
      borderBottomWidth: 1,
      borderBottomColor: "#f3f4f6",
      borderTopLeftRadius: 32,
      borderTopRightRadius: 32,
      backgroundColor: "#f8fafc",
    },
    headerContent: {
      flexDirection: isRTL ? "row-reverse" : "row",
      alignItems: "center",
      justifyContent: "center",
      gap: 8,
    },
    modalHeaderTitle: {
      fontSize: 22,
      color: "#1f2937",
      letterSpacing: 0.5,
      alignSelf: "center",
      textAlign: "center",
      includeFontPadding: false,
      textAlignVertical: "center",
    },
    closeButton: {
      padding: 4,
      borderRadius: 16,
      backgroundColor: "#f3f4f6",
      alignItems: "center",
      justifyContent: "center",
    },
    content: {
      padding: 20,
      backgroundColor: "#fff",
      borderBottomLeftRadius: 32,
      borderBottomRightRadius: 32,
    },
    subtitle: {
      fontSize: 17,
      color: "#6b7280",
      textAlign: "center",
      marginBottom: 20,
      lineHeight: 24,
      fontWeight: "500",
      includeFontPadding: false,
    },
    stagesList: {
      maxHeight: 300,
    },
    stageItem: {
      flexDirection: isRTL ? "row-reverse" : "row",
      justifyContent: "space-between",
      alignItems: "center",
      padding: 16,
      marginBottom: 8,
      borderWidth: 2,
      borderColor: "#e5e7eb",
      borderRadius: 16,
      backgroundColor: "white",

      ...Platform.select({
        ios: {
          shadowColor: "#e0e7ef",
          shadowOffset: { width: 0, height: 1 },
          shadowOpacity: 0.08,
          shadowRadius: 2,
        },
        android: {
          elevation: 1,
        },
      }),
    },
    stageItemSelected: {
      borderColor: "#3b82f6",
      backgroundColor: "#eff6ff",
    },
    stageText: {
      fontSize: 16,
      color: "#374151",
      textAlign: isRTL ? "right" : "left",
      flex: 1,
      includeFontPadding: false,
      textAlignVertical: "center",
    },
    stageTextSelected: {
      color: "#1d4ed8",
      fontWeight: "700",
      textAlign: isRTL ? "right" : "left",
      includeFontPadding: false,
      textAlignVertical: "center",
    },
    stageSelector: {
      paddingVertical: 8,
      paddingHorizontal: 10,
      backgroundColor: theme.background.secondary,
      borderRadius: 8,
      borderWidth: 1,
      borderColor: "#cbd5e1",
      alignItems: "center",
      justifyContent: "center",
    },
    stageSelectorContent: {
      flexDirection: isRTL ? "row-reverse" : "row",
      alignItems: "center",
      justifyContent: "space-between",
      minWidth: 100,
    },
    selectedStageText: {
      fontSize: 12,
      color: "#1e293b",
      fontWeight: "500",
      [isRTL ? "marginLeft" : "marginRight"]: 8,
      textAlign: isRTL ? "right" : "left",
      includeFontPadding: false,
      textAlignVertical: "center",
    },
  });
};
